# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Bierboerse_pb2 as Bierboerse__pb2


class BierboerseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.updateBeers = channel.unary_unary(
                '/de.hadiko.vev.k2.bierboerse.Bierboerse/updateBeers',
                request_serializer=Bierboerse__pb2.UpdateBeerRequest.SerializeToString,
                response_deserializer=Bierboerse__pb2.ServerReply.FromString,
                )
        self.getPrices = channel.unary_unary(
                '/de.hadiko.vev.k2.bierboerse.Bierboerse/getPrices',
                request_serializer=Bierboerse__pb2.PriceRequest.SerializeToString,
                response_deserializer=Bierboerse__pb2.ServerReply.FromString,
                )


class BierboerseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def updateBeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BierboerseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'updateBeers': grpc.unary_unary_rpc_method_handler(
                    servicer.updateBeers,
                    request_deserializer=Bierboerse__pb2.UpdateBeerRequest.FromString,
                    response_serializer=Bierboerse__pb2.ServerReply.SerializeToString,
            ),
            'getPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.getPrices,
                    request_deserializer=Bierboerse__pb2.PriceRequest.FromString,
                    response_serializer=Bierboerse__pb2.ServerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'de.hadiko.vev.k2.bierboerse.Bierboerse', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bierboerse(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def updateBeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/de.hadiko.vev.k2.bierboerse.Bierboerse/updateBeers',
            Bierboerse__pb2.UpdateBeerRequest.SerializeToString,
            Bierboerse__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/de.hadiko.vev.k2.bierboerse.Bierboerse/getPrices',
            Bierboerse__pb2.PriceRequest.SerializeToString,
            Bierboerse__pb2.ServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
