# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Bierboerse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x42ierboerse.proto\x12\x1b\x64\x65.hadiko.vev.k2.bierboerse\x1a\x1fgoogle/protobuf/timestamp.proto\"q\n\x08\x42\x65verage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x17\n\x0fpurchasingPrice\x18\x03 \x01(\x05\x12\x14\n\x0c\x63urrentPrice\x18\x04 \x01(\x05\x12\x0c\n\x04sold\x18\x05 \x01(\x05\x12\x0e\n\x06profit\x18\x06 \x01(\x05\"t\n\tDatapoint\x12\x38\n\tbeverages\x18\x01 \x03(\x0b\x32%.de.hadiko.vev.k2.bierboerse.Beverage\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"B\n\x07History\x12\x37\n\x07history\x18\x01 \x03(\x0b\x32&.de.hadiko.vev.k2.bierboerse.Datapoint\"\x1e\n\nBuyRequest\x12\x10\n\x08\x62uyIndex\x18\x01 \x01(\x05\"E\n\nAddRequest\x12\x37\n\x08\x62\x65verage\x18\x01 \x01(\x0b\x32%.de.hadiko.vev.k2.bierboerse.Beverage\"\x0f\n\rPricesRequest\":\n\x0eHistoryRequest\x12(\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x80\x01\n\x08\x42uyReply\x12\x39\n\toldPrices\x18\x01 \x01(\x0b\x32&.de.hadiko.vev.k2.bierboerse.Datapoint\x12\x39\n\tnewPrices\x18\x02 \x01(\x0b\x32&.de.hadiko.vev.k2.bierboerse.Datapoint2\x95\x03\n\nBierboerse\x12`\n\x0b\x61\x64\x64\x42\x65verage\x12\'.de.hadiko.vev.k2.bierboerse.AddRequest\x1a&.de.hadiko.vev.k2.bierboerse.Datapoint\"\x00\x12_\n\x0b\x62uyBeverage\x12\'.de.hadiko.vev.k2.bierboerse.BuyRequest\x1a%.de.hadiko.vev.k2.bierboerse.BuyReply\"\x00\x12\x61\n\tgetPrices\x12*.de.hadiko.vev.k2.bierboerse.PricesRequest\x1a&.de.hadiko.vev.k2.bierboerse.Datapoint\"\x00\x12\x61\n\ngetHistory\x12+.de.hadiko.vev.k2.bierboerse.HistoryRequest\x1a$.de.hadiko.vev.k2.bierboerse.History\"\x00\x62\x06proto3')



_BEVERAGE = DESCRIPTOR.message_types_by_name['Beverage']
_DATAPOINT = DESCRIPTOR.message_types_by_name['Datapoint']
_HISTORY = DESCRIPTOR.message_types_by_name['History']
_BUYREQUEST = DESCRIPTOR.message_types_by_name['BuyRequest']
_ADDREQUEST = DESCRIPTOR.message_types_by_name['AddRequest']
_PRICESREQUEST = DESCRIPTOR.message_types_by_name['PricesRequest']
_HISTORYREQUEST = DESCRIPTOR.message_types_by_name['HistoryRequest']
_BUYREPLY = DESCRIPTOR.message_types_by_name['BuyReply']
Beverage = _reflection.GeneratedProtocolMessageType('Beverage', (_message.Message,), {
  'DESCRIPTOR' : _BEVERAGE,
  '__module__' : 'Bierboerse_pb2'
  # @@protoc_insertion_point(class_scope:de.hadiko.vev.k2.bierboerse.Beverage)
  })
_sym_db.RegisterMessage(Beverage)

Datapoint = _reflection.GeneratedProtocolMessageType('Datapoint', (_message.Message,), {
  'DESCRIPTOR' : _DATAPOINT,
  '__module__' : 'Bierboerse_pb2'
  # @@protoc_insertion_point(class_scope:de.hadiko.vev.k2.bierboerse.Datapoint)
  })
_sym_db.RegisterMessage(Datapoint)

History = _reflection.GeneratedProtocolMessageType('History', (_message.Message,), {
  'DESCRIPTOR' : _HISTORY,
  '__module__' : 'Bierboerse_pb2'
  # @@protoc_insertion_point(class_scope:de.hadiko.vev.k2.bierboerse.History)
  })
_sym_db.RegisterMessage(History)

BuyRequest = _reflection.GeneratedProtocolMessageType('BuyRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUYREQUEST,
  '__module__' : 'Bierboerse_pb2'
  # @@protoc_insertion_point(class_scope:de.hadiko.vev.k2.bierboerse.BuyRequest)
  })
_sym_db.RegisterMessage(BuyRequest)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUEST,
  '__module__' : 'Bierboerse_pb2'
  # @@protoc_insertion_point(class_scope:de.hadiko.vev.k2.bierboerse.AddRequest)
  })
_sym_db.RegisterMessage(AddRequest)

PricesRequest = _reflection.GeneratedProtocolMessageType('PricesRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRICESREQUEST,
  '__module__' : 'Bierboerse_pb2'
  # @@protoc_insertion_point(class_scope:de.hadiko.vev.k2.bierboerse.PricesRequest)
  })
_sym_db.RegisterMessage(PricesRequest)

HistoryRequest = _reflection.GeneratedProtocolMessageType('HistoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _HISTORYREQUEST,
  '__module__' : 'Bierboerse_pb2'
  # @@protoc_insertion_point(class_scope:de.hadiko.vev.k2.bierboerse.HistoryRequest)
  })
_sym_db.RegisterMessage(HistoryRequest)

BuyReply = _reflection.GeneratedProtocolMessageType('BuyReply', (_message.Message,), {
  'DESCRIPTOR' : _BUYREPLY,
  '__module__' : 'Bierboerse_pb2'
  # @@protoc_insertion_point(class_scope:de.hadiko.vev.k2.bierboerse.BuyReply)
  })
_sym_db.RegisterMessage(BuyReply)

_BIERBOERSE = DESCRIPTOR.services_by_name['Bierboerse']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BEVERAGE._serialized_start=82
  _BEVERAGE._serialized_end=195
  _DATAPOINT._serialized_start=197
  _DATAPOINT._serialized_end=313
  _HISTORY._serialized_start=315
  _HISTORY._serialized_end=381
  _BUYREQUEST._serialized_start=383
  _BUYREQUEST._serialized_end=413
  _ADDREQUEST._serialized_start=415
  _ADDREQUEST._serialized_end=484
  _PRICESREQUEST._serialized_start=486
  _PRICESREQUEST._serialized_end=501
  _HISTORYREQUEST._serialized_start=503
  _HISTORYREQUEST._serialized_end=561
  _BUYREPLY._serialized_start=564
  _BUYREPLY._serialized_end=692
  _BIERBOERSE._serialized_start=695
  _BIERBOERSE._serialized_end=1100
# @@protoc_insertion_point(module_scope)
